[tshark]
path = "C:\\Program Files\\Wireshark\\tshark.exe"
parameters=["-n","-T", "fields","-E", "separator=;","-E", "occurrence=a"]


[[frame]]
label = "TIMESTAMP"
field = "frame.time_epoch"
type  = "float64"

[categories]


[[categories.21]]
label = "TARGET_ADDRESS"
field = "asterix.021_080_VALUE"
type  = "string"

[[categories.21]]
label = "CALLSIGN"
field = "asterix.021_170_VALUE"
type  = "string"

[[categories.21]]
label = "TIME_MSG_RX(s)"
field = "asterix.021_073_VALUE"
type  = "float32"

[[categories.21]]
label = "TIME_MSG_TX(s)"
field = "asterix.021_077_VALUE"
type  = "float32"

[[categories.21]]
label = "INDICADOR_AGE(s)"
field = "asterix.021_295_QI_VALUE"
type  = "float32"

[[categories.21]]
label = "NACV"
field = "asterix.021_090_NUCRNACV"
type  = "uint8"

[[categories.21]]
label = "NIC"
field = "asterix.021_090_NUCPNIC"
type  = "uint8"

[[categories.21]]
label = "SIL"
field = "asterix.021_090_SIL"
type  = "uint8"

[[categories.21]]
label = "NACP"
field = "asterix.021_090_NACP"
type  = "uint8"

[[categories.21]]
label = "SDA"
field = "asterix.021_090_SDA"
type  = "uint8"


